spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 50
        queue-capacity: 10000
      thread-name-prefix: async-task-
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        size: 8
  profiles:
    active: "dev"
